# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0002_token_max_lengths'),
        ('account', '0002_email_max_length'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
