# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub',
            new_name='public',
        ),
    ]
