# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_auto_20160108_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='public',
            new_name='is_public',
        ),
    ]
