# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_auto_20160112_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='kuiqblog, ', max_length=100),
        ),
    ]
